; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@^6.9.0
platform_packages = framework-arduinoespressif32@^3.20017
board = esp32dev
board_build.partitions = min_spiffs.csv
framework = arduino
build_type = release
build_src_filter =
	+<*>
	+<../components/divoom/>
	-<../components/divoom/*_esphome.cpp>
	-<../components/divoom/divoom_component.cpp>
lib_deps =
	WiFi
	ESPmDNS
	BluetoothSerial
	esphome/AsyncTCP-esphome@~2.1.4
	heman/AsyncMqttClient-esphome@~2.1.0
build_unflags = 
	-std=gnu++11
build_flags =
	-std=gnu++17
	-I components/divoom
	-I src
	-DDIVOOM_PLATFORM_PIO
	-DCONFIG_SPIRAM_USE_MALLOC=1
	-DCONFIG_WIFI_LWIP_ALLOCATION_FROM_SPIRAM_FIRST=1
	-DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
	-DCONFIG_BT_ABORT_WHEN_ALLOCATION_FAILS=1
	-DCONFIG_SPIRAM_CACHE_WORKAROUND=1
monitor_filters =
	default
	esp32_exception_decoder
	send_on_enter
monitor_speed = 115200
extra_scripts = post:scripts/flash_images.py

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
	-<*>
	+<../components/divoom/divoom.cpp>
	+<../components/divoom/util.cpp>
	+<../test/shared/>
build_flags =
	-DCONFIG_LWIP_TCP_MSS=1436
	-I components/divoom
	-I test/mocks
extra_scripts = pre:test/inject_project_dir.py

[env:record]
extends = env:native
build_flags = ${env:native.build_flags} -DUPDATE_GOLDENS
